### PR TITLE
Cleanup:  split out unit tests into 2 files

### PR DESCRIPTION
**Pull request by lowell80**
When I created the initial tests for `croniter_range()`, all the test functions where placed under the `CroniterRangeTest` class within the existing `test_croniter.py` file.  But because of the size of the file it's easy to miss that there's two test classes in there.  And it looks like new test are typically just added to the bottom of the file, which is now the `CroniterRangeTest` class, rather than the `CroniterTest` class.

At the end of the day, this is just an organization thing.  The super easy easy alternative "solution" is just to delete the the `
class CroniterRangeTest(base.TestCase):` line entirely, and allow all the functions to exist in a single class.

I tried out some (for me) advanced [git magic](https://stackoverflow.com/a/44036771/315892) that seems to have successfully preserved the history of both test files, so that things like `git blame` still actually shows by-who and when various lines were changed.  (It did required 4 extra commits, unfortunately.)

Note that this technically includes PR #44 due to the fact that I added a new unittest in that commit as well.

### CODE REVIEW

**Comment by kiorky** [comment]
we will wait for #44 to land.

**Comment by lowell80** [comment]
Just merged/resolved conflicts/pushed.

**Comment by kiorky** [comment]
can you rebase ?

**Comment by lowell80** [comment]
Sure, I'll give it a try.

**Pull request merged**
